In [1]:
import os

#Kernal version 3.9.7 

os.environ["GOOGLE_APPLICATION_CREDENTIALS"]="cred.json"
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import os
import numpy as np

In [2]:
data_path= ''
output_dir =  ''
training_data_df = pd.read_csv(data_path + 'data.csv')
training_data_df.head()

,fyear,gvkey,sich,insbnk,understatement,option,p_aaer,new_p_aaer,misstate,act,...,soft_assets,ch_cs,ch_cm,ch_roa,issue,bm,dpi,reoa,EBIT,ch_fcf
0,1990,1009,3460.0,0,0,0,NaN,NaN,0,10.047,...,0.312448,0.095082,0.082631,-0.019761,1,0.413170,0.873555,0.167620,0.161961,-0.042140
1,1990,1011,4841.0,0,0,0,NaN,NaN,0,1.247,...,0.315904,0.188832,-0.211389,-0.117832,1,0.157887,0.745139,-0.428957,-0.157888,0.100228
2,1990,1017,3812.0,0,0,0,NaN,NaN,0,55.040,...,0.605342,0.097551,-0.105780,0.091206,1,2.231337,1.015131,0.394768,0.063681,0.066348
3,1990,1021,3861.0,0,0,0,NaN,NaN,0,24.684,...,0.793068,-0.005725,-0.249704,0.017545,1,1.043582,1.026261,0.094822,0.088347,-0.017358
4,1990,1028,7385.0,0,0,0,NaN,NaN,0,17.325,...,0.869182,-0.231536,-1.674893,-0.466667,0,-1.602508,0.598443,-0.942379,-0.700821,0.130349

In [3]:
scalar = MinMaxScaler(feature_range=(0,1))
X=training_data_df.drop('misstate' ,axis=1)
scaled_training = scalar.fit_transform(training_data_df)

# scaled_test = scalar.fit_transform(test_data_df)

scaled_training_df = pd.DataFrame(data = scaled_training, columns=training_data_df.columns)

In [4]:
scaled_training_df=scaled_training_df.drop(columns=['p_aaer','new_p_aaer'])
scaled_training_df=scaled_training_df.dropna()
scaled_training_df.head()

,fyear,gvkey,sich,insbnk,understatement,option,misstate,act,ap,at,...,soft_assets,ch_cs,ch_cm,ch_roa,issue,bm,dpi,reoa,EBIT,ch_fcf
0,0.0,0.000016,0.339497,0.0,0.0,0.0,0.0,0.000067,0.000094,0.000079,...,0.311332,0.409052,0.514015,0.501581,1.0,0.622087,0.185805,0.993130,0.948638,0.417252
1,0.0,0.000022,0.479034,0.0,0.0,0.0,0.0,0.000010,0.000020,0.000019,...,0.314826,0.414881,0.505350,0.471801,1.0,0.600763,0.152748,0.986486,0.906369,0.437468
2,0.0,0.000041,0.375063,0.0,0.0,0.0,0.0,0.000362,0.000090,0.000288,...,0.607458,0.409206,0.508463,0.535277,1.0,0.773958,0.222250,0.995659,0.935650,0.432657
3,0.0,0.000054,0.380014,0.0,0.0,0.0,0.0,0.000163,0.000099,0.000084,...,0.797256,0.402785,0.504221,0.512910,1.0,0.674745,0.225115,0.992319,0.938909,0.420771
4,0.0,0.000076,0.736082,0.0,0.0,0.0,0.0,0.000115,0.000088,0.000067,...,0.874210,0.388746,0.462222,0.365875,0.0,0.453717,0.114986,0.980768,0.834619,0.441745

In [5]:
X = scaled_training_df.drop('misstate', axis=1).values
Y = scaled_training_df['misstate'].values

In [6]:
import predict as pre
preds=pre.predict_fraud(X[0:10])

In [7]:
preds

[0.0030233263969421387,
 0.0030359625816345215,
 0.0038477182388305664,
 0.005808383226394653,
 0.0028614699840545654,
 0.005061626434326172,
 0.0059129297733306885,
 0.006210356950759888,
 0.008676350116729736,
 0.007431358098983765]